### ISSUE TITLE
Plugin not working with NodeBB v1.12.0

### ISSUE THREAD

**Issue by BlackFayah** [MinecraftForgeFrance/nodebb-plugin-extended-markdown#2]
As the title says. Clicking the buttons in the composer doesn't insert anything, nor does the output look like it should after submitting. Unfortunately, there were no errors in the log.

**Comment by robin4002** [comment]
Hi,
We use this plugin on our forum without any problems.

Ensure that you rebuild NodeBB after installing the plugin.

**Comment by BlackFayah** [comment]
Well, I don't know what to say. I did that yesterday without success, but for some reason it does work now? Strange, must have done something wrong. Anyways, thanks!

**Comment by robin4002** [comment]
Maybe a cache issue. Happy to see that the problem is solved :)
