### ISSUE TITLE
centering text and other functions stopped working when updating to NodeBB 1.13.0

### ISSUE THREAD

**Issue by quokkamole** [MinecraftForgeFrance/nodebb-plugin-extended-markdown#3]
NodeBB 1.12.1 works ok.

However, thiings such as below don't work when I upgrade to NodeBB 1.13.0 :
```
|-centered paragraph-|
```
```
#anchor(title)
```

My Plugin list:
nodebb-plugin-extended-markdown@1.4.0 nodebb-plugin-session-sharing@4.6.3 nodebb-plugin-knowledge-base@1.0.3 nodebb-plugin-node-ldap@1.0.1

**Comment by robin4002** [comment]
Hi,
Yes NodeBB changed the format for the new composer, this partially broke this plugin.
For now I kept my forum in 1.12.2 because I do not have time to correct this bug.

**Comment by robin4002** [comment]
Fixed in version 1.4.1 ;)
