### ISSUE TITLE
anchor for title is considered as a tag...

### ISSUE THREAD

**Issue by MaxWaldorf** [MinecraftForgeFrance/nodebb-plugin-extended-markdown#5]
The first `#anchor()` mention in text is considered as a tag...

Is there a way to change the syntax or stop parsing the anchor tag?

Cheers

**Comment by robin4002** [comment]
Hi,
Sorry, I didn't understood what is the problem.
Can you send a example?

Best regards,

**Comment by MaxWaldorf** [comment]
Simple:

NodeBB consider any word with # as a tag...

Unfortunately, `#anchor` is considered as a tag...
Since you can only put a tag once in the text, the first time you use #anchor() it doesn't translate into a title but in a tag...

The following ones are translated as titles.


--------

Il y a un souci de parsing puisqu'il y a un conflit entre le tag et l'expression title qui utilise `#anchor()` proposée...

A chaque fois la première fois que `#anchor()` est utlisé ça devient un tag et non pas un titre... Par contre, étant donné que NodeBB ne process un tag qu'une fois, les suivants sont bien reconnus...


Donc bref, ça ne marche pas la première fois qu'on l'utilise dans un post mais les suivants (dans le même post) fonctionnent...

**Comment by robin4002** [comment]
I cannot reproduce the issue.
Both on my forum and on my local test instance NodeBB doesn't parse # as a tag.
What is your theme and your extension list ?
Or maybb it's a setting on ACP panel ?

**Comment by MaxWaldorf** [comment]
Here is a list of plugins:

nodebb-plugin-archiver
nodebb-plugin-composer-default
nodebb-plugin-dbsearch
nodebb-plugin-desktop-notifications
nodebb-plugin-emoji
nodebb-plugin-emoji-android
nodebb-plugin-extended-markdown
nodebb-plugin-feed
nodebb-plugin-gravatar
nodebb-plugin-hashtags <-- This one might be the one creating issues
nodebb-plugin-imgur
nodebb-plugin-markdown
nodebb-plugin-mentions
nodebb-plugin-night-mode
nodebb-plugin-openidconnect
nodebb-plugin-poll
nodebb-plugin-question-and-answer
nodebb-plugin-recent-cards
nodebb-plugin-shortcuts
nodebb-plugin-soundpack-default
nodebb-plugin-spam-be-gone
nodebb-plugin-youtube-embed
nodebb-rewards-essentials
nodebb-widget-essentials

This would be maybe interesting to have #anchor removed from potential tags or to change the #anchor syntax to something else...

Cheers

**Comment by MaxWaldorf** [comment]
Ping...

Any updates?

**Comment by robin4002** [comment]
Hi,

Sorry, I was busy.
I installed the plugin `nodebb-plugin-hashtags` on my local test instance and I still cannot reproduce the issue.*

I can put anyway an alternate syntax if you want. Which syntax do you want ? Maybe an additional ! can fix the conflict? (i.e `!#anchor(Title here)`

**Comment by MaxWaldorf** [comment]
That would be nice if you could yes :)

Thank you and happy new year!

**Comment by MaxWaldorf** [comment]
Bump

**Comment by AliCihan** [comment]
@robin4002 we are having the same problem with #anchor as @MaxWaldorf has, with the new hashtags system in NodeBB, it is converted to a tag rather than a title... There are additional problems we had, I wrote them here: 

https://github.com/MinecraftForgeFrance/nodebb-plugin-extended-markdown/issues/6

**Comment by AliCihan** [comment]
@MaxWaldorf this commit solved the issue: 

https://github.com/NodeBB/nodebb-plugin-hashtags/commit/61b87f28c46b2f66ed39f24ea122258a5b8b97cb

**Comment by robin4002** [comment]
Sorry again for my inactivity ...

Awesome! Thanks to barisusakli!
